---
- name: Print list of names
  hosts: localhost
  tasks:
    - name: Print the list of names
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - linux
        - ansible
        - mysql

- name: Installing packages
  hosts: localhost
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-client
        - nginx
        - postfix

- name: Install and uninstall packages
  hosts: localhost
  become: yes
  tasks:
    - name: Install mysql and uninstall others
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'mysql-client', state: 'present' }
        - { name: 'nginx', state: 'absent' }
        - { name: 'postfix', state: 'absent' }