---
- name: Uninstalling packages
  hosts: localhost
  become: yes
  tasks:
    - name: Uninstall or install packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
        - { name: 'mysql', state: 'absent' }
        - { name: 'nginx', state: 'absent' }