---
- name: Print list of names
  hosts: localhost
  tasks:
    - name: Print the list of names
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - linux
        - ansible
        - mysql

