- name: loops
  hosts: localhost
  tasks:
    - name: Prin the list of names
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - linux
        - ansible
        - mysql


- name: Installing packages
  hosts: localhost
  become: yes
  tasks:
    - name: installing Packages 
      ansible.builtin.debug:
        name: "{{ item }}"
        state: latest
      loop:
        - mysql-client
        - nginx
        - postfix


- name: install and uninstall packages
  hosts: localhost
  become: yes
  tasks:
    - name: Install mysql and rest uninstall
      ansible.builtin.debug:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop:
       - { name: 'mysql-client' , state: 'latest'}
       - { name: 'nginx' , state: 'absent'}
       - { name: 'postfix', state: 'absent'}


