- name: install and run nginx
  hosts: web
  become: yes # This is essential for installing packages and managing services
  tasks:
    - name: Ensure Nginx package is installed
      ansible.builtin.package:
        name: nginx
        state: present # Use 'present' to ensure it's installed, 'latest' to upgrade if newer version is available

    - name: Ensure Nginx service is running and enabled on boot
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes 