- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.debug:
      name: nginx
      state: latest
  - name: start nginx
    ansible.builtin.debug:
      name: nginx
      state: started
      enable: yes